#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jul 30 22:32:20 2017

@author: hamsternation
"""

# a practice of generators such as the yield funciton

#def square_numbers(nums):
#    for x in nums:
#        print(x*x)
#
#my_nums = square_numbers([1,2,3,4,5,6])


def square_numbers_generator(num):
    for x in num:
        yield(x*x)

my_generated_nums = square_numbers_generator([1,2,3,4,5,6])

print(next(my_generated_nums))
print(next(my_generated_nums))
print(next(my_generated_nums))
print(next(my_generated_nums))
print(next(my_generated_nums))
print(next(my_generated_nums))


list_comprehension = (x*x for x in range(99999999999))

while input('type no to exit') != 'no':
    print(next(list_comprehension))