#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jul 30 22:44:09 2017

@author: hamsternation
"""

def infinity():
    count = 0
    while True:
        yield count
        count += 1
        
        
list_comprehension = (x for x in infinity())

while input('type no to exit') != 'no':
    print(next(list_comprehension))