#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jul 30 21:40:46 2017

@author: hamsternation
"""

#class numstring:
#    
#    def __init__(self, value):
#        self.value = str(value)
#    
#    def __str__(self):
#        return str(self.value)
#    
#    def __int__(self):
#        return self.value


class Inventory:
    def __init__(self):
        self.slots = []
        
    def add(self, item):
        self.slots.append(item)
    
    def __contains__(self,item):
        return item in self.slots
    
    def __iter__(self):
        yield from self.slots
    
    def __getitem__(self):
        yield from self.slots
food = Inventory()
food.add('crackers')
food.add(('good','stuff'))
food.add({'medicine':'a valuable medication'})

